# Generated by Django 3.0.3 on 2020-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_video_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='videos/covers/'),
        ),
    ]
